version: 2
updates:
- package-ecosystem: npm
  directory: "/site/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - "automerge"

- package-ecosystem: cargo
  directory: "/site/src/quacs-rs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - "automerge"

- package-ecosystem: pip
  directory: "/scrapers/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10